### ISSUE TITLE
Cluster Name in Prompt

### ISSUE THREAD

**Issue by ColonelPanicks** [openflighthpc/flight-starter#1]
Add a cluster name to the prompt (ideally with some nice tool to be able to set that).

Example:
```
[flight@gateway1 (mycluster) ~]$
```

Something like
```
cat << "EOF" > /etc/profile.d/flightcenter.sh
#Custom PS1 with client name
c=32
if [ "$PS1" ]; then
  PS1="[\u@\h\[\e[1;${c}m\] (mycluster)\[\e[0m\] \W]\\$ "
fi
EOF
```

**Comment by mjtko** [comment]
Cluster name added to prompt in 9d4a4c56c10d39a8eb014c25fc22b6d6357be1d3.

(Root-only) tool to configure cluster name added in c78071c6a4844fb919f202daf27c5d0f884daa5e -- use `flight config set cluster.name myclustername` for the magic.
