### ISSUE TITLE
Cluster Name Not In Prompt (Ubuntu 18.04)

### ISSUE THREAD

**Issue by ColonelPanicks** [openflighthpc/flight-starter#2]
## Issue

When setting the cluster name it is expected for it to be shown in the terminal prompt. This works on CentOS but is currently not visible in the terminal on Ubuntu

## Steps to Reproduce

- Launch an Ubuntu 18.04 image on AWS
- Install Flight User Suite
```
sudo apt-key adv --fetch-keys https://repo.openflighthpc.org/openflighthpc-archive-key.asc
sudo apt-add-repository "deb https://repo.openflighthpc.org/openflight/ubuntu stable main"
sudo apt-get update

sudo apt-get install flight-runway flight-env flight-desktop flight-starter
```
- Logout & back in
- Activate the environment and set permanently on
```
flight start
flight set always on
```
- Set cluster name
```
flight config set cluster.name scooby
```
- Logout & back in
- No name in prompt!

**Comment by mjtko** [comment]
Fixed via 2e13f3499b040f8a7d777734347c75b5bb28914d.
